neofs-adm: init and update-contracts are the only commands for wallets creation
nspcc-dev/neofs-node pull request #2515
Opened 2023-08-16 14:11 UTC by AliceInHunterland

added checks for commands before wallet creation

Closes #2134.

2023-08-16 18:57 UTC, roman-khimov requested changes
Likely we also need to limit `newInitializeContext` to call `openContractWallet` only when this wallet is really neded, that's not the case for `set-config`, for example (check `ContractWallet` uses).

2023-08-16 18:57 UTC, roman-khimov commented on cmd/neofs-adm/internal/modules/morph/generate.go
> +	if cmd.Name() != "init" {
I don't think this is needed and it's likely to break `generate-alphabet` command.

2023-08-17 14:22 UTC, cthulhu-rider approved these changes

2023-08-17 14:51 UTC, roman-khimov approved these changes

2023-08-17 14:51 UTC, merged