conrtol: set the highest priority for control service.
nspcc-dev/neofs-node pull request #2645
Opened 2023-11-14 10:29 UTC by AliceInHunterland

Closes: #2585.

2023-11-14 11:46 UTC, roman-khimov commented on cmd/neofs-node/control.go
> +	go func() {
Why async? It can start at any point in time then.

2023-11-14 13:04 UTC, roman-khimov reviewed
IR?

2023-11-15 13:21 UTC, carpawell reviewed
The commit starts with "conrtol".

2023-11-16 19:54 UTC, roman-khimov commented
Needs to be rebased.

2023-11-17 09:20 UTC, cthulhu-rider requested changes
commit header ends with a period. It is unclear from the text that priority has been maxed for both SN and IR

2023-11-17 09:20 UTC, cthulhu-rider commented on CHANGELOG.md
> +- The priority of running control service is increased (#2585)
if `set the highest priority`, then `maximized`

2023-11-17 09:20 UTC, cthulhu-rider commented on pkg/innerring/innerring.go
> +		lis, err := net.Listen("tcp", controlSvcEndpoint)
`err` is lost

btw best to start listening immediately after parsing the keys in order to respond to an error as early as possible, and only if everything is ok - init gRPC server

2023-11-20 14:09 UTC, carpawell approved these changes

2023-11-20 14:29 UTC, merged