Support JSON marshalers for placement policy
nspcc-dev/neofs-node pull request #27
Opened 2020-09-15 14:18 UTC by fyrchik

Support marshaling to JSON.

2020-09-15 14:56 UTC, realloc requested changes

2020-09-15 14:56 UTC, realloc commented on pkg/policy/json.go
> +		CBF       uint32     `json:"backup_factor,omitempty"`
Let's keep it `container_backup_factor` everywhere. It may be confused with object backup factor or some other meaning.

2020-09-15 16:03 UTC, cthulhu-rider commented on pkg/policy/json.go
> +// ToJSON creates placement policy from JSON.
`// FromJSON`

2020-09-15 16:06 UTC, cthulhu-rider approved these changes

2020-09-17 07:34 UTC, alexvanin approved these changes

2020-09-17 07:36 UTC, merged