node/placement: use predefined error for empty netmap
nspcc-dev/neofs-node pull request #2916
Opened 2024-08-13 12:54 UTC by carpawell

https://github.com/nspcc-dev/neofs-sdk-go/pull/615 was merged, and it is now possible to use the error. Commit includes SDK update _without_ new API adoption.

2024-08-14 16:39 UTC, carpawell commented
Oh, changing SDK significantly for months... Let this PR be a reminder, I do not expect it to adopt SDK.

2024-08-20 13:52 UTC, carpawell commented
Ok, fixed. But I was surprised how inconvenient is now SDK for eacl tables constructing in the apps like our CLI.

2024-08-20 19:26 UTC, roman-khimov approved these changes

2024-08-21 11:52 UTC, cthulhu-rider requested changes

2024-08-21 11:52 UTC, cthulhu-rider commented on cmd/neofs-cli/modules/util/acl.go
> +	var ok bool
`r, ok := `

2024-08-21 11:52 UTC, cthulhu-rider commented on cmd/neofs-cli/modules/bearer/create.go
> +		table, err := eaclSDK.Unmarshal(raw)
```suggestion
		table, err := eaclSDK.UnmarshalJSON(raw)
```

2024-08-21 11:52 UTC, cthulhu-rider commented on cmd/neofs-cli/modules/util/acl.go
> +	var records []eacl.Record
final length is known

2024-08-21 11:52 UTC, cthulhu-rider commented on cmd/neofs-cli/internal/common/eacl.go
> +	table, err = eacl.Unmarshal(data)
what was wrong with previous code?

2024-08-21 14:14 UTC, carpawell commented on cmd/neofs-cli/modules/bearer/create.go
> +		table, err := eaclSDK.Unmarshal(raw)
my bad

2024-08-21 14:14 UTC, carpawell commented on cmd/neofs-cli/internal/common/eacl.go
> +	table, err = eacl.Unmarshal(data)
> Table should be created using one of the constructors.

updated docs say so

2024-08-21 16:06 UTC, cthulhu-rider commented on cmd/neofs-cli/internal/common/eacl.go
> +	table, err = eacl.Unmarshal(data)
u already have an instance

2024-08-21 16:08 UTC, cthulhu-rider approved these changes

2024-08-21 16:10 UTC, merged