cli: Don't print help and don't skip `defer`ed funcs on failures
nspcc-dev/neofs-node pull request #2942
Opened 2024-09-19 08:34 UTC by End-rey

Closes #623, #2890.

In `neofs-cli` I add func `common.WrapError` that wrap error to `custom_errors.ExitErr` and return it on every error, But I doubt it. Maybe it is necessary to wrap only the first appearance of this error, or vice versa, only the last one.

2024-09-19 19:25 UTC, roman-khimov reviewed
Conflicts, rebase pls. But looks nice in general. Probably we can add some tests for it as well.

2024-09-19 19:25 UTC, roman-khimov commented on cmd/neofs-cli/internal/common/exit.go
> +func WrapError(errFmt string, err error) *custom_errors.ExitErr {
I'd probably do it as `WrapError(err error)` and leave `fmt.Errorf()` to the caller if and when needed. You still can unwrap internally to get the code, but formatting would be easier, I think. You can have cases like `"smth (additional data: %d): %w"` and this won't fit the current interface.

2024-09-19 19:25 UTC, roman-khimov commented on CHANGELOG.md
> +- `defer` func is not skipped in cobra-based programs (#2942)
Not sure it makes sense for outside reader, but don't have immediate suggestions either.

2024-09-20 06:52 UTC, cthulhu-rider requested changes
in total, lux gut

afaik #623 can be resolved purely independent, so its better to dedicate a separate small (last) commit for it to not mix with heavy #2890.

also tag intermediate commits with `Refs #2890.`

2024-09-20 06:52 UTC, cthulhu-rider commented on cmd/neofs-adm/internal/modules/storagecfg/root.go
> +				if err != nil {
this never happens for `flag==true`, i think the condition should be
```go
if flag, err := getConfirmation(false, "Continue configuration? yes/[no]: "); flag || err != nil {
	return err
}
```

2024-09-20 06:52 UTC, cthulhu-rider commented on cmd/neofs-cli/internal/common/exit.go
> +func WrapError(errFmt string, err error) *custom_errors.ExitErr {
it should not return pointers to be compliant with `ExitOnErr` making
```go
var e ExitErr
if !errors.As(err, &e) {
	e.Code = 1
}
```
easy to check
```go
func TestExit(t *testing.T) {
	custom_errors.ExitOnErr(common.WrapError("context; %w", common.ErrAwaitTimeout))
}
```
expected `3`, got `1`

2024-09-20 06:52 UTC, cthulhu-rider commented on cmd/neofs-cli/internal/client/sdk.go
> +		return nil, common.WrapError("can't create API client: %w", err)
i dont think this is a good place to throw `ExitErr`, this is the responsibility of `RunE`s. So, just `return nil, fmt.Errorf(...)`

2024-09-20 06:52 UTC, cthulhu-rider commented on cmd/neofs-cli/internal/common/exit.go
> +	if errors.As(err, &exitErr) {
having this means that code does not care who makes `ExitErr` while it should. Imo normally this should never be true. The most stable approach is to wrap by `RunE` functions only

2024-09-20 06:52 UTC, cthulhu-rider commented on cmd/neofs-cli/internal/common/eacl.go
> +		return eacl.Table{}, WrapError("", errors.New("incorrect path to file with EACL"))
here too enough to `return eacl.Table{}, errors.New("incorrect path to file with EACL")` and let caller how to wrap it. With this, u wont need to wrap all function returns

2024-09-20 06:52 UTC, cthulhu-rider commented on cmd/neofs-lens/internal/meta/get.go
> +		return common.Errf("invalid address argument: %w", err)
`common.Errf` made sense with `ExitOnErr` func since it allowed to avoid `if` statement. Now we should use `fmt.Errorf` (and purge `Errf`)

2024-09-23 16:25 UTC, End-rey commented
Now, in the `neofs-cli`, func `common.WrapError` is used after receiving the `cobra` command error in `main`.

2024-09-24 05:00 UTC, cthulhu-rider approved these changes
still suggest to ref first 3 commits to #2890 https://github.com/nspcc-dev/neofs-node/pull/2942#pullrequestreview-2317317501

2024-09-24 13:22 UTC, roman-khimov commented on cmd/neofs-cli/modules/object/hash.go
> +	cli, _ := internalclient.GetSDKClientByFlag(ctx, commonflags.RPC)
Not handled.

2024-09-24 13:22 UTC, roman-khimov commented on cmd/neofs-cli/modules/object/head.go
> +			if err != nil {
Looks like `return err` for both cases.

2024-09-24 13:22 UTC, roman-khimov commented on cmd/neofs-cli/modules/object/range.go
> +				return err
Just `return err`, no need for `nil` check, you don't wrap it anyway.

2024-09-24 15:03 UTC, roman-khimov approved these changes

2024-09-24 19:34 UTC, merged