metabase: save last epoch when metabase was resynchronized
nspcc-dev/neofs-node pull request #2966
Opened 2024-10-09 10:31 UTC by End-rey

Closes #2887.

2024-10-09 19:52 UTC, roman-khimov reviewed
I think we also need some lens command that will show it, otherwise what's the point. And this command should be aware of different mb versions.

2024-10-09 19:52 UTC, roman-khimov commented on pkg/local_object_storage/metabase/db.go
> +func (db *DB) SaveLastResyncEpoch() {
Why a separate method, why not a part of `Reset()`?

2024-10-10 01:06 UTC, carpawell requested changes

2024-10-10 01:06 UTC, carpawell commented on pkg/local_object_storage/metabase/db.go
> +	db.info.LastResyncEpoch = currEpoch
how can we use it? every time we restart application this field is lost. i planned to extend metabase storage with a number that is filled every reset and is read every start

2024-10-10 01:07 UTC, carpawell commented
> I think we also need some lens command that will show it

But there is nothing it will show us in the current PR...

2024-10-10 16:47 UTC, End-rey commented
Now, the last epoch when the metabase was resynchronized is saved at db in the `shardInfoBucket` with the key `last_resync_epoch`, when metabase is `init` with `reset == true` flag and it is read to `info` field every `init`.

Also, make `lens` command, but don't understand what does it means.
> this command should be aware of different mb versions.

2024-10-14 18:32 UTC, carpawell commented on pkg/local_object_storage/metabase/control.go
> +		} else {
just a little suggestion: if now we have both branches (if-else) i would prefer not to use negation (`!reset`), i think it would be read simpler

2024-10-14 18:32 UTC, carpawell commented on pkg/local_object_storage/metabase/last_resync_epoch_test.go
> +	require.NoError(t, db.Reset())
can we add a single non-zero test case, please?
1. empty base
2. empty to non-empty
3. non-empty to non-empty
4. non-empty reload with no changes

i gues that is the full list of use cases and we are ready to be confident

2024-10-15 14:11 UTC, carpawell approved these changes

2024-10-15 14:20 UTC, roman-khimov approved these changes
Migrated DBs will just return 0, right?

2024-10-15 14:46 UTC, merged