cli: fix overriding of the `Timestamp` container attribute
nspcc-dev/neofs-node pull request #2985
Opened 2024-10-28 17:41 UTC by End-rey

Closes #1339.

2024-10-28 19:37 UTC, carpawell approved these changes

2024-10-28 19:37 UTC, carpawell commented on cmd/neofs-cli/modules/container/create.go
> +			return errors.New("empty attribute value")
can we add key with empty attribute to the error msg?

2024-10-29 07:27 UTC, cthulhu-rider requested changes
there are also `--name` and `--global-name` attributty flags, they should be treated the same

also https://github.com/nspcc-dev/neofs-node/issues/1339#issuecomment-1110650798 suggests to cover object attributes similarly within this issue, the current one is not enough to close the issue

2024-10-29 07:27 UTC, cthulhu-rider commented on cmd/neofs-cli/modules/container/create.go
> +		if kvPair[0] == "" {
emptiness checks aint related to the timestamp so deserve a separate commit

2024-10-29 11:05 UTC, cthulhu-rider commented on cmd/neofs-cli/modules/object/put.go
> +
there are also lifetime flags `-e` or `-l` setting `__NEOFS__EXPIRATION_EPOCH` which can be `kv[0]`. They also must not cause duplication or conflict

2024-10-29 14:49 UTC, roman-khimov approved these changes

2024-10-29 14:49 UTC, roman-khimov commented on cmd/neofs-cli/modules/container/create.go
> +				"you need to use one of them or make it equal")
make them equal

2024-10-29 15:03 UTC, cthulhu-rider approved these changes
@End-rey resolve conflicts and go

2024-10-29 16:07 UTC, merged