Upgrade NeoGo
nspcc-dev/neofs-node pull request #3040
Opened 2024-12-03 19:31 UTC by roman-khimov

2024-12-03 20:14 UTC, roman-khimov commented
Blocked by https://github.com/nspcc-dev/neofs-testcases/pull/903.

2024-12-03 22:23 UTC, carpawell requested changes
Linter dead.

2024-12-04 07:03 UTC, roman-khimov commented
It's fixed already, but for whatever reason GH can't process the branch update (see above).

2024-12-09 08:15 UTC, cthulhu-rider approved these changes

2024-12-09 09:54 UTC, carpawell approved these changes

2024-12-09 11:56 UTC, merged