Fix/make version be flag in CLI
nspcc-dev/neofs-node pull request #624
Opened 2021-06-18 06:46 UTC by carpawell

Closes #571.

2021-06-21 10:10 UTC, cthulhu-rider commented on cmd/neofs-cli/modules/root.go
> +	if err == nil && printVersion {
Looks like we can ignore error
```
printVersion, _ := cmd.Flags().GetBool("version")
if printVersion {}
```

2021-06-21 10:14 UTC, cthulhu-rider commented
Everything is good. Small suggestion: replace
```
cmd.PrintErrln(fmt.Errorf(...))
```
with
```
cmd.PrintErrf(...)
```

2021-06-21 10:14 UTC, cthulhu-rider approved these changes

2021-06-21 13:33 UTC, carpawell reviewed
@cthulhu-rider, if use `cmd.PrintErrf(...)` then it is necessary to write smth like `cmd.PrintErrf("message: %s\n", err)` without `"%w"` and with `"\n"`, is it ok?

2021-06-23 06:57 UTC, alexvanin requested changes

2021-06-23 06:57 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +		cmd.PrintErrln()
```suggestion
		cmd.PrintErrln(err)
```

2021-06-23 06:57 UTC, alexvanin commented on cmd/neofs-cli/modules/container.go
> +			cmd.PrintErrln()
```suggestion
			cmd.PrintErrln(err)
```

2021-06-23 07:05 UTC, carpawell commented on cmd/neofs-cli/modules/object.go
> +		cmd.PrintErrln()
fixed

2021-06-23 07:08 UTC, alexvanin approved these changes

2021-06-23 07:08 UTC, merged