[#79] Implement object commands
nspcc-dev/neofs-node pull request #96
Opened 2020-10-15 14:34 UTC by fyrchik

Implement everything except `Search`.

2020-10-16 08:52 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +		base58.Encode(cid.ToV2().GetValue()))
With https://github.com/nspcc-dev/neofs-node/pull/98 you can just  `cmd.Printf("  ID: %s\n  CID: %s\n", oid, cid)`

2020-10-16 08:52 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +		new(client.ObjectHeaderParams).WithAddress(objAddr),
Consider parsing `--main-only` flag. If set, then add `.WithMainFields()` option.

2020-10-16 08:52 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +	objectHashCmd.Flags().String("type", hashSha256, "Hash type. Either 'sha256' (default) or 'tz'")
Default value specified automatically by Cobra, so you don't have to comment about this. 
Now help line looks
```
      --type string     Hash type. Either 'sha256' (default) or 'tz' (default "sha256")
```

2020-10-16 08:52 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +	objectHashCmd.Flags().StringSlice("range", []string{}, "Range to take hash from.")
Add an example `in a form of 1:2,3:4`

2020-10-16 08:52 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +		base58.Encode(objAddr.GetContainerID().ToV2().GetValue()))
See message about available stringer interface.

2020-10-16 08:52 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +	cmd.Printf("OID: %s\n", base58.Encode(obj.GetID().ToV2().GetValue()))
See message about available stringer interface.

2020-10-16 10:00 UTC, alexvanin requested changes

2020-10-16 10:00 UTC, alexvanin commented on cmd/neofs-cli/modules/object.go
> +	cmd.Printf("Checksum: %s\n", hex.EncodeToString(obj.GetPayloadChecksum().GetSum()))
Let's add object type information there. Something like this:
```
	switch obj.GetType() {
	case object.TypeRegular:
		cmd.Println("Type: regular")
	case object.TypeTombstone:
		cmd.Println("Type: tombstone")
	case object.TypeStorageGroup:
		cmd.Println("Type: storage group")
	default:
		cmd.Println("Type: unknown")
	}
```

2020-10-16 13:09 UTC, fyrchik commented on cmd/neofs-cli/modules/object.go
> +	if len(raw) == 0 {
Fixed.

2020-10-19 11:34 UTC, alexvanin approved these changes

2020-10-19 11:35 UTC, merged